FROM "ubuntu:bionic"

MAINTAINER chamalgomes166@outlook.com

RUN apt-get update \
  && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip

RUN pip3 install jupyter

WORKDIR usr/local/bin/DataScience

RUN jupyter notebook --generate-config --allow-root
RUN echo "c.NotebookApp.password = u'sha1:6a3f528eec40:6e896b6e4828f525a6e20e5411cd1c8075d68619'" >> /root/.jupyter/jupyter_notebook_config.py

CMD ["jupyter", "notebook", "--allow-root", "--notebook-dir=/usr/local/bin/Datascience/", "--ip=0.0.0.0", "--port=8888", "--no-browser"]
